### ISSUE TITLE
invalid regex causes site to crash for user

### ISSUE THREAD

**Issue by abhishekg999** [firasdib/Regex101#1745]
## Bug Description
The following invalid regex:
```
(?<![!\\\\])\\[(?:[a-zA-Z_ ]+(?:\\\\[\\[\\]\\(\\)\\!`]+)*)+[a-zA-Z]*\\]\\((.*?|\\n.+?|.+?\\n|\\n.+?\\n)\\)
```
causes site to crash after a few seconds + interaction with the explanation panel.

### Reproduction steps
Paste regex in regular expression text field. Wait a few seconds, and interact with the explanation panel (clicking on regex in panel).
Site with crash for user.

### Expected Outcome
Site should not crash.

### Browser
Include browser name and version
Chrome 99.0.4844.51, 64 bit.

### OS
Include OS name and version
Windows 10 Version 10.0.19042 Build 19042

**Comment by abhishekg999** [comment]
vendors-sentry.3c48beaa1c350deabc3a.chunk.js:2 TypeError: Cannot read properties of null (reading 'charClassSubtraction')

Error reported in console

**Comment by firasdib** [comment]
Thank you. I have a fix locally, but it'll be a while until its live.

**Comment by abhishekg999** [comment]
I am curious to know, what is the cause of it?

**Comment by firasdib** [comment]
Its a null pointer exception :). Looks to be when you hover the token in the input box. 


Vänliga hälsningar / Best regards,

Firas Dib

**Comment by Spirits-** [comment]
I'd like to add another invalid regex that causes the site to fail:

`\w+[-])?[0-9]+`

Paste this into the pattern field, click out of it (for example into the text field) and back into the pattern field and the site will crash. Error source seems to be the same, at least according to the dev console:

```
vendors-sentry.3c48beaa1c350deabc3a.chunk.js:2 TypeError: Cannot read properties of null (reading 'charClassSubtraction')
    at bundle.48aa5478185fb6462c01.js:1:306986
    at bundle.48aa5478185fb6462c01.js:1:308080
    at La (bundle.48aa5478185fb6462c01.js:1:313774)
    at Ma (bundle.48aa5478185fb6462c01.js:1:313977)
    at Ro (bundle.48aa5478185fb6462c01.js:1:359218)
    at aa (vendors-bundle.8e594180e95a2b735f3a.js:2:302312)
    at $a (vendors-bundle.8e594180e95a2b735f3a.js:2:311830)
    at Ul (vendors-bundle.8e594180e95a2b735f3a.js:2:355333)
    at Ls (vendors-bundle.8e594180e95a2b735f3a.js:2:341633)
    at Es (vendors-bundle.8e594180e95a2b735f3a.js:2:341561)
    at Cs (vendors-bundle.8e594180e95a2b735f3a.js:2:341424)
    at vs (vendors-bundle.8e594180e95a2b735f3a.js:2:338411)
    at vendors-bundle.8e594180e95a2b735f3a.js:2:288234
    at vendors-bundle.8e594180e95a2b735f3a.js:2:452018
    at Ui (vendors-bundle.8e594180e95a2b735f3a.js:2:288011)
    at Gi (vendors-bundle.8e594180e95a2b735f3a.js:2:288179)
    at qi (vendors-bundle.8e594180e95a2b735f3a.js:2:288114)
    at De (vendors-bundle.8e594180e95a2b735f3a.js:2:359115)
    at vendors-bundle.8e594180e95a2b735f3a.js:2:279689
    at _r (vendors-bundle.8e594180e95a2b735f3a.js:2:279729)
    at Xt (vendors-bundle.8e594180e95a2b735f3a.js:2:267795)
    at Qt (vendors-bundle.8e594180e95a2b735f3a.js:2:267021)
    at vendors-bundle.8e594180e95a2b735f3a.js:2:452018
    at Yt (vendors-bundle.8e594180e95a2b735f3a.js:2:266871)
(anonymous) @ vendors-sentry.3c48beaa1c350deabc3a.chunk.js:2
```

**Comment by firasdib** [comment]
Yeah, its the same problem. Thank you

**Comment by firasdib** [comment]
Thanks, this will be fixed in the upcoming release.
