### ISSUE TITLE
C# generated code fails with Unrecognized escape sequence \\N.

### ISSUE THREAD

**Issue by PaulEPetersen** [firasdib/Regex101#1938]
## Bug Description
When generating c# code using the \N works in the https://regex101.com/ website but putting the generated code into c# doesnt work

System.Text.RegularExpressions.RegexParseException
  HResult=0x80070057
  Message=Invalid pattern '(?<date>\d{2}\/\d{2}\/\d{4})\,\s(?<time>\d{2}:\d{2})\s-\s(?<message>.*\n{0,1}(((?!\d\d\/\d\d\/\d\d)\N*\n){0,}))' at offset 101. Unrecognized escape sequence \\N.
  Source=System.Text.RegularExpressions
  StackTrace:
   at System.Text.RegularExpressions.RegexParser.ScanCharEscape()
   at System.Text.RegularExpressions.RegexParser.ScanBasicBackslash(Boolean scanOnly)
   at System.Text.RegularExpressions.RegexParser.ScanBackslash(Boolean scanOnly)
   at System.Text.RegularExpressions.RegexParser.CountCaptures()
   at System.Text.RegularExpressions.RegexParser.Parse(String pattern, RegexOptions options, CultureInfo culture)
   at System.Text.RegularExpressions.Regex.Init(String pattern, RegexOptions options, TimeSpan matchTimeout, CultureInfo culture)
   at System.Text.RegularExpressions.Regex..ctor(String pattern, RegexOptions options, TimeSpan matchTimeout, CultureInfo culture)
   at System.Text.RegularExpressions.RegexCache.GetOrAdd(String pattern, RegexOptions options, TimeSpan matchTimeout)
   at System.Text.RegularExpressions.Regex.Matches(String input, String pattern, RegexOptions options)
   at TestProject.Example.aMain2() in ......cs:line 419
   at TestProject......DecomposeText() in ......cs:line 21

### Reproduction steps
generate c# regex using https://regex101.com/ using \N

### Expected Outcome
the regex works in C#

### Browser
N/A

### OS
Windows 11

**Comment by PaulPetersenAtTheAA** [comment]
I don't know, I would guess. Net hasn't implemented hence the problem. The generator should only generate working code IMHO

**Comment by working-name** [comment]
It generates example code for a specific language you choose, but it doesn't interpret and translate regex from one flavor to another - that would be a rather huge undertaking and at times impossible because there isn't always an alternate way of doing something.

Generally if you select the target flavor (.net) while you're developing the regex you're going to get feedback on things not implemented - although it could also be the site not running the latest and greatest .net build for example. Either way, it's probably less headache than finding out like this.

Hope this helps 😃
