### ISSUE TITLE
Entering pipe character('or' character) crashes the website

### ISSUE THREAD

**Issue by amirsoroush** [firasdib/Regex101#2038]
## Bug Description

![image](https://user-images.githubusercontent.com/114881632/230671718-38a25f8d-3a05-4b55-a892-1ae7b96c80cd.png)

When Python flavor is selected, entering `|` character as the pattern causes the website to crash and redirects to the error page which says:
```none
A critical error has occurred
If possible, open up an issue with as many details as you can here: https://github.com/firasdib/Regex101/issues.

It might be a good idea to take a screen shot of your dev console window, if you know how to open it.
```

It produces this log in the browser's console:
```none
bundle.ed7ec165f22421099536.js:1 App initialized - version 9.0.3
bundle.ed7ec165f22421099536.js:1 Loaded initial state
bundle.ed7ec165f22421099536.js:1 Store configured
bundle.ed7ec165f22421099536.js:1 Successfully registered service worker
vendors-sentry.a42db56f15ec3a0de339.chunk.js:1 TypeError: Cannot read properties of undefined (reading 'flags')
    at bundle.ed7ec165f22421099536.js:1:145864
    at b.runMatch (bundle.ed7ec165f22421099536.js:1:146140)
    at bundle.ed7ec165f22421099536.js:1:356724
    at il (vendors-bundle.789c10b0eea8105864c7.js:2:164790)
    at ku (vendors-bundle.789c10b0eea8105864c7.js:2:184912)
    at vendors-bundle.789c10b0eea8105864c7.js:2:183654
    at Su (vendors-bundle.789c10b0eea8105864c7.js:2:183719)
    at uu (vendors-bundle.789c10b0eea8105864c7.js:2:177475)
    at Fi (vendors-bundle.789c10b0eea8105864c7.js:2:118203)
    at vendors-bundle.789c10b0eea8105864c7.js:2:174880
(anonymous) @ vendors-sentry.a42db56f15ec3a0de339.chunk.js:1
fa @ vendors-bundle.789c10b0eea8105864c7.js:2
(anonymous) @ vendors-bundle.789c10b0eea8105864c7.js:2
Io @ vendors-bundle.789c10b0eea8105864c7.js:2
xl @ vendors-bundle.789c10b0eea8105864c7.js:2
wl @ vendors-bundle.789c10b0eea8105864c7.js:2
bl @ vendors-bundle.789c10b0eea8105864c7.js:2
(anonymous) @ vendors-bundle.789c10b0eea8105864c7.js:2
Su @ vendors-bundle.789c10b0eea8105864c7.js:2
uu @ vendors-bundle.789c10b0eea8105864c7.js:2
Fi @ vendors-bundle.789c10b0eea8105864c7.js:2
(anonymous) @ vendors-bundle.789c10b0eea8105864c7.js:2
``` 

### Reproduction steps

1. Open https://regex101.com/
2. Choose "Python" flavor.
3. Insert `55011859` into the "text string" section.
4. Insert bare `|` character into the "regular expression" section.

You'll see the crash.

**Note:** It only happens when I choose "python" flavor. It's OK with the rest of them. 

### Browser
Google Chrome - Version 112.0.5615.49 (Official Build) (64-bit)

### OS
Pop!_OS 22.04 LTS x86_64

**Comment by firasdib** [comment]
Thank you, I will have this resolved asap.
