### ISSUE TITLE
PCRE2: Critical Error when within unclosed \Q (no \E)

### ISSUE THREAD

**Issue by OnlineCop** [firasdib/Regex101#2094]
## Bug Description
When PCRE2 is selected, typing `\Q` followed by several characters results in a Critical Error.

Here is the JavaScript console log:

```javascript
vendors-sentry.b29f5a739da549c23ea2.chunk.js:1
TypeError: Cannot read properties of undefined (reading 'split')
    at p (bundle.e13fcb29569c298e4951.js:1:26368)
    at Cs (vendors-bundle.bb3c5ea5fa667a8da99d.js:2:135348)
    at Oa (vendors-bundle.bb3c5ea5fa667a8da99d.js:2:146969)
    at Ca (vendors-bundle.bb3c5ea5fa667a8da99d.js:2:146177)
    at ka (vendors-bundle.bb3c5ea5fa667a8da99d.js:2:145782)
    at Cl (vendors-bundle.bb3c5ea5fa667a8da99d.js:2:195504)
    at wu (vendors-bundle.bb3c5ea5fa667a8da99d.js:2:181332)
    at yu (vendors-bundle.bb3c5ea5fa667a8da99d.js:2:181260)
    at vu (vendors-bundle.bb3c5ea5fa667a8da99d.js:2:181123)
    at su (vendors-bundle.bb3c5ea5fa667a8da99d.js:2:177930)
    at uu (vendors-bundle.bb3c5ea5fa667a8da99d.js:2:178319)
    at Fi (vendors-bundle.bb3c5ea5fa667a8da99d.js:2:119194)
    at vendors-bundle.bb3c5ea5fa667a8da99d.js:2:175871
(anonymous) @ vendors-sentry.b29f5a739da549c23ea2.chunk.js:1
fa @ vendors-bundle.bb3c5ea5fa667a8da99d.js:2
(anonymous) @ vendors-bundle.bb3c5ea5fa667a8da99d.js:2
Io @ vendors-bundle.bb3c5ea5fa667a8da99d.js:2
xl @ vendors-bundle.bb3c5ea5fa667a8da99d.js:2
wl @ vendors-bundle.bb3c5ea5fa667a8da99d.js:2
bl @ vendors-bundle.bb3c5ea5fa667a8da99d.js:2
(anonymous) @ vendors-bundle.bb3c5ea5fa667a8da99d.js:2
Su @ vendors-bundle.bb3c5ea5fa667a8da99d.js:2
uu @ vendors-bundle.bb3c5ea5fa667a8da99d.js:2
Fi @ vendors-bundle.bb3c5ea5fa667a8da99d.js:2
(anonymous) @ vendors-bundle.bb3c5ea5fa667a8da99d.js:2
setTimeout (async)
(anonymous) @ vendors-sentry.b29f5a739da549c23ea2.chunk.js:1
w @ vendors-bundle.bb3c5ea5fa667a8da99d.js:2
i @ vendors-sentry.b29f5a739da549c23ea2.chunk.js:1
setTimeout (async)
(anonymous) @ vendors-sentry.b29f5a739da549c23ea2.chunk.js:1
(anonymous) @ vendors-bundle.bb3c5ea5fa667a8da99d.js:2
S @ vendors-bundle.bb3c5ea5fa667a8da99d.js:2
(anonymous) @ bundle.e13fcb29569c298e4951.js:1
(anonymous) @ bundle.e13fcb29569c298e4951.js:1
(anonymous) @ bundle.e13fcb29569c298e4951.js:1
update @ vendors-bundle.bb3c5ea5fa667a8da99d.js:2
(anonymous) @ vendors-bundle.bb3c5ea5fa667a8da99d.js:2
dispatch @ vendors-bundle.bb3c5ea5fa667a8da99d.js:2
jn @ vendors-bundle.bb3c5ea5fa667a8da99d.js:2
flush @ vendors-bundle.bb3c5ea5fa667a8da99d.js:2
(anonymous) @ vendors-bundle.bb3c5ea5fa667a8da99d.js:2
```

### Reproduction steps
1. Select flavor PCRE2.
2. Enter `\Q` and continue adding characters: `\Q () `.
3. About this point, the page displays "A critical error has occurred".

### Expected Outcome
An unterminated `\Q` should behave as though `\E` were implicitly appended to the pattern.

### Browser
Chromium (Chrome, Vivaldi), Firefox, Edge

### OS
Windows, MacOS (have not tried Linux).

**Comment by firasdib** [comment]
Thank you, fixed locally.

**Comment by Melissafrance** [comment]
#1540
