### ISSUE TITLE
Regex with variable width look-behind didn't work in python 2.7 but no error is shown in regex101

### ISSUE THREAD

**Issue by FL1989** [firasdib/Regex101#285]
Hello,

its the first time i try to use regex, so i tried some code on your internet site. In the regex tester it works how i want. But if i copy the code from the code generator it always apperas an error called: "error: look-behind requires fixed-width pattern"

here is the code:
```
import re
p = re.compile(ur'(?<=_|\b)CQ(?=_|\b)')
test_str = u"CQ Station 1 CQ CQ \"CQ_T\" \"T_CQ\" CQA \"CQ\" aCQ CQa sCQ _CQ_ \\CQ\\ CQ< CQ- CQ) CQ! CQ/ =CQ >CQ (CQ ACQA DFGCQ"
subst = u"SP"
result = re.sub(p, subst, test_str)
```

Code in regex Tester:
```
"(?<=_|\b)CQ(?=_|\b)"           g
Test string:
CQ Station 1 CQ CQ \"CQ_T\" \"T_CQ\" CQA \"CQ\" aCQ CQa sCQ _CQ_ \\CQ\\ CQ< CQ- CQ) CQ! CQ/ =CQ >CQ (CQ ACQA DFGCQ
Substitution:
SP
Result:
SP Station 1 SP SP \"SP_T\" \"T_SP\" CQA \"SP\" aCQ CQa sCQ _SP_ \\SP\\ SP< SP- SP) SP! SP/ =SP >SP (SP ACQA DFGCQ
```
Thanks for your help

**Comment by nhahtdh** [comment]
I hope I recreate the regex and test cases correctly

https://regex101.com/r/tU0dF4/1

In Python 3.2.5:

```
>>> re.compile(r'(?<=_|\b)CQ(?=_|\b)')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.2/re.py", line 214, in compile
    return _compile(pattern, flags)
  File "/usr/lib/python3.2/re.py", line 280, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/usr/lib/python3.2/sre_compile.py", line 496, in compile
    code = _code(p, flags)
  File "/usr/lib/python3.2/sre_compile.py", line 481, in _code
    _compile(code, p.data, flags)
  File "/usr/lib/python3.2/sre_compile.py", line 116, in _compile
    raise error("look-behind requires fixed-width pattern")
sre_constants.error: look-behind requires fixed-width pattern
```

**Comment by FL1989** [comment]
Yeah thats right. Same error in Python 3.2.5!?

**Comment by nhahtdh** [comment]
Would you mind editing your report to place the code inside code block with 3 backticks?

**Comment by FL1989** [comment]
I am sorry but i dont know what "backticks" are. my english isnt very well. Hope I had done something in my first post what you meaned.

**Comment by nhahtdh** [comment]
See https://guides.github.com/features/mastering-markdown/, under Syntax Highlighting.

**Comment by FL1989** [comment]
Here is my error:
```
Traceback (most recent call last):
  File "<ipython-input-4-8bbf7352b615>", line 1, in <module>
    runfile('D:/reTest.py', wdir='D:')
  File "D:\WinPython-64bit-2.7.9.3\python-2.7.9.amd64\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 680, in runfile
    execfile(filename, namespace)
  File "D:\WinPython-64bit-2.7.9.3\python-2.7.9.amd64\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 71, in execfile
    exec(compile(scripttext, filename, 'exec'), glob, loc)
  File "D:/reTest.py", line 2, in <module>
    p = re.compile(br'(?<=_|\b)CQ(?=_|\b)')
  File "D:\WinPython-64bit-2.7.9.3\python-2.7.9.amd64\lib\re.py", line 194, in compile
    return _compile(pattern, flags)
  File "D:\WinPython-64bit-2.7.9.3\python-2.7.9.amd64\lib\re.py", line 251, in _compile
    raise error, v # invalid expression
error: look-behind requires fixed-width pattern
```

**Comment by firasdib** [comment]
Interesting, I will adjust this. I assume this happens for all anchors? `^` and `$` too?

**Comment by FL1989** [comment]
If I use this code:
```
(\b|(?<=_))CQ((?=_)|\b)
```
no error message would given.
Thanks for your help

**Comment by nhahtdh** [comment]
@firasdib How did you provide support for Python?

**Comment by nhahtdh** [comment]
I think there is a regression on this bug. The permalink in the bug report above no longer gives an error.

**Comment by firasdib** [comment]
@nhahtdh Can you verify if this is still an issue in v2?

**Comment by nhahtdh** [comment]
The issue in this report has been fixed. However, `(?<=_|(a))` is incorrectly rejected. Should I open a new issue or continue from the private repo?

**Comment by firasdib** [comment]
Alright, lets continue tracking it internally and close this issue.
