### ISSUE TITLE
Bad python regex doesn't give errors

### ISSUE THREAD

**Issue by Brachi** [firasdib/Regex101#288]
In Python, the following regex doesn't compile, but does work in regex101:

(?<=src="|http://www.example.com)\S+\.gif'

```
>>> re.compile('(?<=src="|http://www.example.com)\S+\.gif')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.4/re.py", line 219, in compile
    return _compile(pattern, flags)
  File "/usr/lib/python3.4/re.py", line 288, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/usr/lib/python3.4/sre_compile.py", line 469, in compile
    code = _code(p, flags)
  File "/usr/lib/python3.4/sre_compile.py", line 454, in _code
    _compile(code, p.data, flags)
  File "/usr/lib/python3.4/sre_compile.py", line 109, in _compile
    raise error("look-behind requires fixed-width pattern")
sre_constants.error: look-behind requires fixed-width pattern
```

Python 2.7:

```
>>> re.compile('(?<=src="|http://www.example.com)\S+\.gif')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/re.py", line 190, in compile
    return _compile(pattern, flags)
  File "/usr/lib/python2.7/re.py", line 244, in _compile
    raise error, v # invalid expression
sre_constants.error: look-behind requires fixed-width pattern
>>> 
```

**Comment by firasdib** [comment]
Related to #285
