### ISSUE TITLE
Lookbehind of variable length should throw an error (Python)

### ISSUE THREAD

**Issue by ByteCommander** [firasdib/Regex101#499]
See this example: https://regex101.com/r/iA3jY8/1

It uses the following Python regex:

    (?<=\n|\A)start of line

However, as `\A` (start of line) and `\n` (newline character) have different lengths, this should not be allowed. It works in the online tester though.

Here is what happens in the Python console:

```
$ python3
Python 3.5.1+ (default, Mar 30 2016, 22:46:26) 
[GCC 5.3.1 20160330] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import re
>>> re.search(r'(?<=\n|\A)start of line', 'just any text to test', re.DOTALL)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.5/re.py", line 173, in search
    return _compile(pattern, flags).search(string)
  File "/usr/lib/python3.5/re.py", line 293, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/usr/lib/python3.5/sre_compile.py", line 540, in compile
    code = _code(p, flags)
  File "/usr/lib/python3.5/sre_compile.py", line 525, in _code
    _compile(code, p.data, flags)
  File "/usr/lib/python3.5/sre_compile.py", line 158, in _compile
    raise error("look-behind requires fixed-width pattern")
sre_constants.error: look-behind requires fixed-width pattern
>>> 
```

**Comment by nhahtdh** [comment]
Dup of this issue https://github.com/firasdib/Regex101/issues/285, I guess.
